### ISSUE TITLE
will there be a hyperscript interface?

### ISSUE THREAD

**Issue by iambumblehead** [patrick-steele-idem/morphdom#103]
will there be a hyperscript interface?

I've been using [hyperscript-helpers](https://github.com/ohanhi/hyperscript-helpers) which allows one to use hyperscript functions with engines that provide a hyperscript interface such as virtual-dom or react. I'd like like to use morphdom and am wondering if there will be a hyperscript interface for morphdom

```
ul('#bestest-menu', items.map( item =>
  li('#item-'+item.id, attrs(item.id), item.title))
);
```

**Comment by AutoSponge** [comment]
@iambumblehead I've built a few things with hyperscript and morphdom, it's a good fit. However, morphdom only does the merge, how you produce your DOM is up to you. In your example, call morphdom passing your generated view and the target element (or document.body).
