### ISSUE TITLE
Add pkg.module key to support external rollup uses

### ISSUE THREAD

**Issue by orestis** [patrick-steele-idem/morphdom#104]
Hi,

I'm using rollup to bundle morphdom into my own applications. Since morphdom already uses ES2015 modules, it is as simple as adding a [pkg.module](https://github.com/rollup/rollup/wiki/pkg.module) entry to `package.json` to enable this:

```
  "module": "src/index.js",
```

I'm not an export on this whole ecosystem, but using a temporary fork with just this allowed rollup with `rollup-plugin-node-resolve` to correctly identify and bundle morphdom into my bundle.

Thanks!

**Comment by snewcomer** [comment]
added an es2015 && module entry #115 

try out 2.5.2!
