### ISSUE TITLE
element with textnode flashes when nothing has changed

### ISSUE THREAD

**Issue by Cordemans** [patrick-steele-idem/morphdom#106]
I noticed a lot of flashes in the element inspector for elements that did not actually changed.
When I removed the text inside those elements, they did not flash anymore.

In this example you will notice - at least with **Firefox** and the **element inspector** open - that the element with text keeps flashing and the other element without any text does not flash:
[https://jsfiddle.net/ufc3wazq/2/](https://jsfiddle.net/ufc3wazq/2/)

Should the nodeValue for a TEXT_NODE only be updated when its value actually changed?

**Comment by bendulum** [comment]
Same problem here!

**Comment by AutoSponge** [comment]
I only see a single flash when the example starts. Even when I add a counter to the text value that increases with each interval, all intervals are smooth except the first. I'm not sure if that's morphdom or jsfiddle resetting the results canvas.

**Comment by patrick-steele-idem** [comment]
I put some checks to only set the `nodeValue` on the text nodes if the old value doesn't match the new value. Please let me know if that helped, but like @AutoSponge, I am not convinced there was a problem with morphdom. 

Which browser were you seeing the flashing in? Do you still see the flashing with `morphdom@2.3.3`?

**Comment by Cordemans** [comment]
Thanks! I can confirm that the flashing does not occur in `morphdom@2.3.3`

See image for an example what I see in Firefox 54 with `morphdom@2.3.2`:

![morphdom 106](https://user-images.githubusercontent.com/2056801/27136428-920b25f6-511b-11e7-99b2-d69690f63ff4.gif)
