### ISSUE TITLE
Bug when adding new selected option to select

### ISSUE THREAD

**Issue by mAAdhaTTah** [patrick-steele-idem/morphdom#107]
Reproducible example:

https://jsfiddle.net/jamesdigioia/n228vv3t/

In Chrome, this appears as "blue" being selected after the render. Inspecting the DOM reveals that two options have `select`, the previously selected option as well as the new one.

**Comment by AutoSponge** [comment]
Even adding un-selected options to the select will cause the value to change to the first added option.

This needs some research.

**Comment by mtyaka** [comment]
#117 fixes this.

JSFiddle using the patched morphdom: https://jsfiddle.net/4j3a7ux7/1/

**Comment by AutoSponge** [comment]
@mtyaka awesome, thanks!

**Comment by snewcomer** [comment]
fixed and published as 2.5.1
