### ISSUE TITLE
Can morphdom be used with hyperscript in a way that is not awkward.

### ISSUE THREAD

**Issue by iambumblehead** [patrick-steele-idem/morphdom#110]
My applications use hyperscript, but morphdom uses strings, so it would seem that, in order to use morphdom, I'll need to do so with a hyperscript interface that stringifies HTML --is this true? If so, it seems awkward and discourages me from using morphdom.

**Comment by whiteinge** [comment]
Morphdom works with any hyperscript implementation that can produce vanilla DOM elements. So it works just fine with the OG [hyperscript](https://github.com/hyperhype/hyperscript) project.

**Comment by AutoSponge** [comment]
Morphdom render is an "overloaded" method--it can take two nodes or a node and a string. For a long time, it didn't take strings. So, the main purpose of morphdom is to work with nodes. Strings were added later.
