### ISSUE TITLE
Not work for table elements?

### ISSUE THREAD

**Issue by halfnibble** [patrick-steele-idem/morphdom#116]
Does morphdom not work for individual table elements? 
E.g. `<td>` elements?

I can use morphdom successfully with `<h1>` tags, but whenever I try to run morphdom on `<tr>` or `<td>` tags, it loses the dom element.

This will actually break the DOM and render "Jamie" instead of `<td id="testEl2">Jamie</td>` causing the table itself to break. 

    var testEl2 = document.getElementById('testEl2');
    morphdom(testEl2, '<td id="testEl2">Jamie</td>');

**Comment by AutoSponge** [comment]
I've never tried to apply morphdom to a single cell. A row or table makes sense to me but a cell seems like too much work. Can you create a demo using fiddle, jsbin, etc?

**Comment by patrick-steele-idem** [comment]
Please try putting your tr in a tbody or thead. If you put a tr directly as a child of a table then the browser will automatically introduce a tbody and this can cause problems with dom diffing

**Comment by halfnibble** [comment]
I'm guessing this has to do with the String to DOM process. Is it just creating a `<div>` and running `.innerHTML` to create the DOM nodes? If so, that would explain why `<tr>` and `<td>` don't work as a string, but they DO work when I `document.createElement('<tr>/<td>')` and run morphdom with DOM as the second argument.
