### ISSUE TITLE
onBeforeElUpdated surprising behavior?

### ISSUE THREAD

**Issue by sandro-pasquali** [patrick-steele-idem/morphdom#118]
I may just be missing something, but I was surprised how I was unable to cancel an element update with 
```
morphdom(targ, newContent, { 
  onBeforeElUpdated(fromEl) { 
    if(thisIsTheTextarea) return false; 
  }
})
```
...in the following widget (notably with sub-widgets):
```
<widgetA>
  <widgetB>
  <textarea><!-- this should survive morphs but is blanked whenever widgetA morphs --></textarea>
</widgetA>
```
The problem is fixed by removing `<widgetB>`:
```
<widgetA>
  <textarea><!-- now a survivor! --></textarea>
</widgetA>
```
It is also fixed by changing ordering:
```
<widgetA>
  <textarea><!-- survivors come first! --></textarea>
  <widgetB>
</widgetA>
```
And fixed by "wrapping" the sub-widget in a `<div>`:
```
<widgetA>
  <div>
    <widgetB>
  </div>
  <textarea><!-- this content will survive morphs --></textarea>
</widgetA>
```
Just wondering if this is expected or documented somewhere. Apologies if I'm missing something obvious.

**Comment by vans163** [comment]
Your not closing <widgetB> ? where is the /

**Comment by snewcomer** [comment]
I'm not sure there is enough information.  I think the above comment is correct ^^
