### ISSUE TITLE
issues with file size

### ISSUE THREAD

**Issue by sido420** [patrick-steele-idem/morphdom#121]
I tried comparing library's size (as per github) and one on wizard.in and i found a huge difference.

https://wzrd.in/standalone/morphdom@latest is approx. 4.8K and https://raw.githubusercontent.com/patrick-steele-idem/morphdom/master/dist/morphdom-umd.min.js is 10k+ 

You can visit the links to see the difference.

Whats the difference between the two?

**Comment by snewcomer** [comment]
This should be ~4kb minified.
