### ISSUE TITLE
Custom element properties are lost in IE8 on DOM patch

### ISSUE THREAD

**Issue by truefusion** [patrick-steele-idem/morphdom#122]
I have some properties on the element level. When I make a call to patch the DOM, those properties are lost.

Minimal reproducible code:
```
var tree = render()
,   elm  = document.querySelector('#element')
;
elm.asdf = 'asdf';
console.log(elm.asdf);
morphdom(elm, tree);
console.log(elm.asdf);
```

While I've managed to work around the issue, I have not tested it beyond IE8 except in Chrome (and, of course, it works as expected in Chrome).

**Comment by AutoSponge** [comment]
Unless that's a supported property (like `elm.id = 'foo'`) you'll need to use `setAttribute('asdf', 'asdf')`. What you've done is set an object property on the DOM instance which is not reflected in the attributes list. That's what morphdom needs to render correctly.
