### ISSUE TITLE
Is this project still being supported?

### ISSUE THREAD

**Issue by Javiani** [patrick-steele-idem/morphdom#130]
Hi! First of all, thanks for this amazing library!!!
I used with along my own component library and it's fantastic... 

I got a package called `reactor` which is a combination of Morphdom with [sodajs](https://github.com/AlloyTeam/sodajs)

The combination of these 2 projects are the best thing ever... I'm wondering why these 2 projects have the last commit from 1 year ago... Have you give up?

I'm working with these projects for a while and they both work so great, I'm really concerned about the support... Please don't drop it...

If you can't continue with Morphdom, can you please suggest me an alternative that can get a html as input and updates a target node with diffing?

Thanks!

**Comment by ricardobeat** [comment]
My understanding is that the marko.js framework has it's own version of morphdom in it's source: https://github.com/marko-js/marko/tree/master/src/morphdom

Seems like it diverged more and more until this one was abandoned. Not sure why this is the case - we still use morphdom and would love being able to stay up to date too.

**Comment by liabadi** [comment]
+1
I integrated Morphdom into one of my company's largest services (>400M monthly sessions), and its impact on the product's interactivity was amazing.

**Comment by max0xff** [comment]
I love morphdom, It's all I ever needed for DOM manipulations.

I'm using it in all my projects and it's really good experience for me. I've composed my own framework around it, using redux and mustache templates.

I like that morphdom doesn't include other stuff, like event handling, template system, routing and etc, so I can choose by myself. Also the performance is absolutly awesome. One of the best tools in my js arsenal.

**Comment by Javiani** [comment]
@max0xff , Please! Share your framework with us! I'm a framework creator myself I'd love to know more about it and learn something new..

If there's anyone interested, I created this package for my own library : 
https://medium.com/jails-org/one-of-my-major-concerns-since-the-very-beginning-was-how-to-make-an-easy-to-use-template-system-a0b0cb2bd47c

@patrick-steele-idem, morphdom is awesome!!! Please this is the best open-source project I have ever used, please, keep it alive, it's decoupled, it's fast... It should compete with React Fiber. I got several projects that kills React performance by far, all of them using Morphdom indirectly.

**Comment by patrick-steele-idem** [comment]
For the time being, I have had to take a break from open source to balance work and life demands. If someone is interested in being added as a maintainer please let me know. Sorry for the inconvenience and long delay in responding.

**Comment by moderntimesmedia** [comment]
IIRC Phoenix (a Ruby On Rails-ish framework) will be using morphdom for a new feature (LiveView): https://dockyard.com/blog/2018/12/12/phoenix-liveview-interactive-real-time-apps-no-need-to-write-javascript

Even though the Phoenix and Elixir ecosystem isn't exactly large, I'm sure there'll be more people interested in using and supporting morphdom as a result...

**Comment by Javiani** [comment]
> For the time being, I have had to take a break from open source to balance work and life demands. If someone is interested in being added as a maintainer please let me know. Sorry for the inconvenience and long delay in responding.

I would love to be helping on support, but to be honest, my knowledge regarding rendering technics on browser is pretty low... It would be nice to have some help from people who already have some experience on this kind of problem, in order to keep the high quality standard.

I have no relevance on js community, perhaps the best thing is somebody who have some relevance to post this on medium or some other channel to spread out the project needs.

**Comment by snewcomer** [comment]
@patrick-steele-idem I would be interested in helping maintain/support this project.  I'm not directly contributing to LiveView (Phoenix), but a part of the team that is developing it.  Would definitely be a reliable steward if you are still interested in having ppl help maintain/respond to issues/improve.

**Comment by patrick-steele-idem** [comment]
@snewcomer Sorry for the delayed response (my day job still keeps me really busy so I am still taking a break from open source and I don't notice most GitHub notifications). It sounds like your team would be a good steward of this project. I'm happy to work with you guys offline on the details of adding the appropriate folks as maintainers.

**Comment by snewcomer** [comment]
Closing for now as this library is important for phoenix live_view.  Will be creating and adding more issues in the next few weeks.  Feel free to reach out!

https://github.com/phoenixframework/phoenix_live_view

**Comment by ricardobeat** [comment]
@snewcomer awesome! Thanks for stepping in.

**Comment by calebporzio** [comment]
This is really great to see, thanks @snewcomer !!

**Comment by pranav-js** [comment]
@snewcomer so are you still supporting it?
