### ISSUE TITLE
move to org

### ISSUE THREAD

**Issue by DanielRuf** [patrick-steele-idem/morphdom#131]
Please move this repo to some org to ease the future maintenance of this repo and increase the truck factor. Also this makes it easier to maintain as we can use groups and different permissions then.

**Comment by patrick-steele-idem** [comment]
I'm not opposed to that. Are you interested in being added as a maintainer?

**Comment by DanielRuf** [comment]
> I'm not opposed to that.

Why that? Maintenance, teams with different permissions, truck factor, ... all things which are relevant.

**Comment by patrick-steele-idem** [comment]
I think you misunderstood my comment. I am agreeing with you. But if I move it over to a new org who should I add as maintainers?

**Comment by DanielRuf** [comment]
Hm, good question as I am already very active in a few projects.
What would be the next steps?

* resolve open issues
* merge PRs which fix issues
* cut a new release (needs proper rights on npmjs and so on)
* check who might be considered as maintainer(s)
* triage open StackOverflow questions?

**Comment by DanielRuf** [comment]
I see there is interest by users who also use it in larger projects at https://github.com/patrick-steele-idem/morphdom/issues/130

**Comment by snewcomer** [comment]
Will be resolving, creating and adding more issues in the next few weeks. 

In the meantime 2.5 has been released!  Lmk if you have any questions!
