### ISSUE TITLE
Input element losing value when typing + morphing

### ISSUE THREAD

**Issue by vans163** [patrick-steele-idem/morphdom#134]
I seem to have read through the closed comments and documentation but cannot find a way to make what I type into an input element persist after the morph. 

For a test I am calling morph on the input element with a 2 second timeout and typing into the input element. The element is `<input></input>` without a value set in both the old and new elements. I simply want what I typed into the old to carry over into the new.

**Comment by brucou** [comment]
I may be having a similar problem to yours. However a code example would be really appreciated to analyze your issue.

**Comment by snewcomer** [comment]
This could be handled in morphdom.  We handle this ourselves [here](https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L443) in live view.  I'll put it on the docket to work on this week or next.

**Comment by snewcomer** [comment]
@vans163 We would have to leave this up to you as it would require us tracking "focused" state.  Here is how you can do it in your own code.

```
      onBeforeElUpdated: function(fromEl, toEl) {
        let focused = document.activeElement;
        if(isTextualInput(fromEl) && fromEl === focused) {
          mergeInputs(fromEl, toEl)
          return false
        } else {
          return true
        }
      }
```

```
      mergeAttrs(target, source){
        source.getAttributeNames().forEach(name => {
          let value = source.getAttribute(name)
          target.setAttribute(name, value)
        })
      },
```

**Comment by snewcomer** [comment]
Let me know if this works for you!  closing for now
