### ISSUE TITLE
selectbox selected diffing bug

### ISSUE THREAD

**Issue by vans163** [patrick-steele-idem/morphdom#136]
It seems when I switch tabviews the same value inside the selectbox selected option is in the other tab.

Both tabs have the same select box. After a few more morphs this goes away.

**Comment by max0xff** [comment]
Hi, not sure if this will help you, but... usually when I switch views I try to put id on the view template, to make it easy for the diff algo :)

**Comment by vans163** [comment]
I think this is the result of extra bootstrap4 tabs javascript interaction and the correct solution is to burn all JS

**Comment by snewcomer** [comment]
Lmk if you have other issues.  If you want to burn all JS, this solution may seem appealing :)

https://github.com/chrismccord/phoenix_live_view
