### ISSUE TITLE
Destroying and Re-adding elements instead of "moving" them

### ISSUE THREAD

**Issue by calebporzio** [patrick-steele-idem/morphdom#152]
The Issue:

When a node is added in the middle of siblings, the siblings below will be discarded, and then re-added, instead of just moved. Is this intended? I'm running into issues where the focus states are being lost, and temporary DOM states like "value" and such in these elements.

Below is a CodePen (screenshot and link) that demonstrates my issue:
![image](https://user-images.githubusercontent.com/3670578/56934432-e5e51380-6ab9-11e9-9340-a6be7126a7bc.png)

https://codepen.io/calebporzio/pen/XQQxXY?editors=1010

I would think that morphdom would be smart enough to preserve the elements and not have to destroy and re-create.

Let me know if this is unintended behavior and I'm happy to help dig deep, just want to make sure I'm not barking up the wrong tree.

**Comment by calebporzio** [comment]
On second thought, this is standard behavior of any dom-diffing algorithm right? This is why you need `:key` attributes in Vue or React for adding `<li>` elements.

I think it just struck me as odd at first glance, but this seems to be standard behavior.

I'll wait for confirmation from someone else.

**Comment by calebporzio** [comment]
On third thought, the reason I thought it would NOT need a "key" attribute, is because the tagNames are distinct. I understand why moving around `<li>`s would need a "key", but just didn't think distinct tag names would. Either way, my guess could be off.

**Comment by AutoSponge** [comment]
This is where vdom libraries can perform better. They can take into account the entire tree before making changes. morphdom is a tree walker and backtracking (and holding references) is expensive (especially on large doms). The algorithm complexity and compute power needed has, previously, made this a non-starter. Something like focus management is left to the implementer (via hooks and such). If you can make headway on a better algorithm I'd be happy to evaluate it.

**Comment by calebporzio** [comment]
Gotcha, good to hear I'm not crazy. We'll see what comes of this. I'm not well versed in dom-diffing algos, but maybe if the itch gets bad enough I'll scratch it. Glad it's being used in a big project like LiveView so some of these things will get more attention.

**Comment by snewcomer** [comment]
@calebporzio Looks like 2.4 had the fix!  morphdom is targeting only that specific element and after it is done traversing the `currentToNode`, it is done iterating. Lmk if you see something different and feel free to re-open if need be 👍 

https://github.com/patrick-steele-idem/morphdom/blob/master/CHANGELOG.md#254

And yes, managing focus state is possible as I'm sure you are already aware!

https://github.com/phoenixframework/phoenix_live_view/blob/7231d6ef92cf41a43cf4e1571aefaecc1de14828/assets/js/phoenix_live_view.js#L722
