### ISSUE TITLE
Morphdom is "updating" elements that are the exact same

### ISSUE THREAD

**Issue by calebporzio** [patrick-steele-idem/morphdom#153]
![image](https://user-images.githubusercontent.com/3670578/56934602-7c193980-6aba-11e9-9c72-ca9a7e7f1085.png)

According to the screenshot, (and my personal experience), Morphdom thinks it needs to update elements that are the exact same.

I have found this is because of lines like: https://github.com/patrick-steele-idem/morphdom/blob/master/src/morphdom.js#L199

Where "isSameNode" is used to detect equality. isSameNode checks for equality by reference, and because we are passing in plain text or a different node as the "toEl", it will ALWAYS return false, therefore "updating" things it shouldn't.

My personal fix for this has been replacing all the instances of "isSameNode" with "isEqualNode" and that seems to have worked fairly well, but I know there are compatibility issues with that approach.

I just thought I'd get the conversation started as this seems like such an oversight, I must be missing some understanding on my end.

Anyone else run into this?

**Comment by snewcomer** [comment]
@calebporzio 👋 This can be handled in `onBeforeElUpdated`.  It may be the same node by reference depending on how the user applies morphdom.  Perhaps the toEl is the original fromEl but with something appended to it.  

Any further thoughts?

https://github.com/patrick-steele-idem/morphdom#can-i-make-morphdom-blaze-through-the-dom-tree-even-faster-yes
https://github.com/phoenixframework/phoenix_live_view/pull/131

**Comment by calebporzio** [comment]
So, I might be naive here, but I would think if toEl is the original fromEl, if it had something appended to it, fromEl would too. Right? Reference is a reference? Exact same thing? Or am I missing something - thanks for the response.

And thanks for picking up work on this repo @snewcomer. I'm creating a LiveView-like tool called Livewire for the Laravel community, and it puts me at ease knowing someone has taken things over here.

**Comment by calebporzio** [comment]
Ah, I did some digging and found this:
https://github.com/choojs/nanocomponent#whats-a-proxy-node

This explains why morphdom uses isSameNode() -> it is there for people to overload the isSameNode function. Probably mostly for people using morphdom with their own vDom libraries.

I see that the general consensus is to leave the "isSameNode" calls in morphdom and just push people towards checking "isEqualNode" in their "onBeforeElUpdated" hooks.

I personally think this should somehow be addressed as it's probably the most common use case, and having to add the check in a global hook feels a bit tacked-on to me.

**Comment by AutoSponge** [comment]
Sorry for my absence. I originally contributed the `isSameNode` code. You're correct that under normal use it will always be `false` but when used as an expando property to override the prototype method, it can be used to "skip" evaluation as you noted in the choo example.

**Comment by snewcomer** [comment]
@calebporzio 👋 Hope all is well.  I think there are two issues.  

One is updating nodes when `isEqualNode` for the subtree is true.  We have this in Phoenix Live View [here](https://github.com/phoenixframework/phoenix_live_view/blob/master/assets/js/phoenix_live_view.js#L726).  The question is should this be a part of `morphdom`. 

The second is the element proxies via `isSameNode`.  There are two PR's: #156 && #155.  Is this something that needs to be fixed and which one do you think is the best path forward?

**Comment by calebporzio** [comment]
Hey @snewcomer, Thanks for taking the time to look into this. I think your PR (#156) seems best for now, however, I don't know what @ AutoSponge  was saying about this slowing the package down. If that's negligible, I'd say, this is a good step forward.

As you mentioned, this is a separate issue from converting `isSameNode` to `isEqualNode` (which I think still should be done). Until that's done, this change will just add overhead to frameworks like Livewire and LiveView.

**Comment by snewcomer** [comment]
Closing for now!  I would have a hard time putting down exactly why we have added/subsequently taken out the `isEqualNode` optimization in LiveView but suffice to say, we have noticed issues.  A global hook is still the recommended approach for now!
