### ISSUE TITLE
Morphdom messed up with the form select 

### ISSUE THREAD

**Issue by olivierbossel** [patrick-steele-idem/morphdom#154]
Surely a small issue but it's anoying.

https://codesandbox.io/embed/14624qpoz4
1. Select an option
2. Click rerender
3. The select is being reseted

Hope this can be fixed without too much effort.
Thanks in advance!

**Comment by AutoSponge** [comment]
You need to update the state of the selected option to render `selected`. Morphdom is doing exactly what was asked.

This requires adding an event handler to listen for change on the input, then when you re-render, check to see if the `selected` option index changed and update the html string accordingly.

**Comment by olivierbossel** [comment]
ok thanks for the feedback. appreciate that!
I will do as you say. 
Cheers!
