### ISSUE TITLE
[Bug] Possibly reverse value asignment for INPUT elements

### ISSUE THREAD

**Issue by nesterow** [patrick-steele-idem/morphdom#157]
Hello,
Following code assigns value from `target` element to `source` element. If I understand correctly, it should be vice-versa. i.e `toEl.value = fromEl.value`;
```javascript
// src/specialElHandlers.js
{
   INPUT: function(fromEl, toEl) {
        syncBooleanAttrProp(fromEl, toEl, 'checked');
        syncBooleanAttrProp(fromEl, toEl, 'disabled');

        if (fromEl.value !== toEl.value) {
            fromEl.value = toEl.value;  // <--- 
        }

        if (!toEl.hasAttribute('value')) {
            fromEl.removeAttribute('value');
        }
    },
}
```
[specialElHandlers.js#L48](https://github.com/patrick-steele-idem/morphdom/blob/da08ab419ae21d305bc5cfb38f2f3d6c2152d1c7/src/specialElHandlers.js#L48)

**Comment by snewcomer** [comment]
Yeah it is a bit of a misnomer.  As we walk the tree, we morph the `from` based on the `to`.

https://github.com/patrick-steele-idem/morphdom/blob/master/src/morphdom.js#L326

**Comment by nesterow** [comment]
This function simply deletes value attribute form input if `toEl.value` is an empty string because the next condition would return true. Some js frameworks can loose binding to the 'value' attribute. I suspect this is why i cannot bind value after morphing.  I'm using  RiotJS

**Comment by nesterow** [comment]
I mean if the value property were set using javascript `InputElement.hasAttribute('value')` would return 'false' anyway

**Comment by AutoSponge** [comment]
In general, it's bad idea to morph inputs. It can cause focus loss, caret position changes, etc.

We're not tracking the `value` attribute here. The `value` property is what's being changed. Do you have a test case that doesn't make the expected change?

**Comment by nesterow** [comment]
This function forks correctly. Sorry, I was mislead by confusing variable naming. The issue was that the input values were set a moment after morphdom was called. Thanks for your answers!
