### ISSUE TITLE
There should be some defensive code or a hint in the README？

### ISSUE THREAD

**Issue by cbbfcd** [patrick-steele-idem/morphdom#160]
This is a great implementation, thanks to the author's contribution.
When I learned this tool (forgive me for using it as a tool in a project), I had a confusion:

```javascript
function createFragmentFromStr(str) {
  let frag = document.createElement("template");
  frag.innerHTML = str;
  document.body.appendChild(frag.content.firstChild);
}
// if i input a str like `       <li>hello morphdom!</li>`
//  it will not works, unless `str.trim()` frist.
```
I think this should be the details that the user should pay attention to. 
but, If there not a plan to add defensive code to the `toEl` method or other place.
there should hava a prompt it in the README?
I think this is a very easy to overlook detail, which may cause the user to have problems. Confused.
if need a PR, my pleasure.

**Comment by snewcomer** [comment]
A PR would be appreciated with `str.trim()`. Thanks!
