### ISSUE TITLE
Morphdom is not a function

### ISSUE THREAD

**Issue by isabellachen** [patrick-steele-idem/morphdom#162]
I am using [yo-yo](https://github.com/maxogden/yo-yo) which uses morphdom to update the dom. The library requires morphdom and uses it:

```
var morphdom = require('morphdom')
module.exports.update = function (fromNode, toNode, opts) {
  if (!opts) opts = {}
  if (opts.events !== false) {
    if (!opts.onBeforeElUpdated) opts.onBeforeElUpdated = copier
  }

  return morphdom(fromNode, toNode, opts)
}
```

However, this triggers an error, "morphdom is not a function". 
I see that morphdom is being exported  like so:

`module.exports = morphdom;`

This is causing the export to be an object, so in order to use morphdom, I have to call morphdom.default()

Not sure how best to handle this ...

**Comment by snewcomer** [comment]
👋 Is the library itself broken or your application that uses yo-yo?

**Comment by isabellachen** [comment]
My application uses yoyo. I'm starting to think it might be a webpack issue actually, gonna try a few things and get back to you 🤪

**Comment by snewcomer** [comment]
@isabellachen Any updates?  I'll close for now but please reopen if need be!
