### ISSUE TITLE
x-templates possible?

### ISSUE THREAD

**Issue by cmnstmntmn** [patrick-steele-idem/morphdom#170]
Hei, i'm curious if it's possible to use in x-templates like

```
<script type="text/x-marko">
   <h3>{{ variable }}</h3>
  
   or 

   <h3>${variable}</h3>
</script>
```

**Comment by snewcomer** [comment]
@cmnstmntmn 👋 Are you trying to diff these x-templates?  Do you have an example that isn't working?

**Comment by cmnstmntmn** [comment]
@snewcomer hmm, i don't remember how i solve that issue; way to old :))
