### ISSUE TITLE
scripts do not execute when added.

### ISSUE THREAD

**Issue by logankeenan** [patrick-steele-idem/morphdom#178]
When a script is added to the page either through a script with a `src` attribute or an inline script it will not download the script or execute the inline code.  Is this expected behavior? 

Thank you!

Edit: 

This does execute script tags which have a src attribute
```js
{
    onNodeAdded: function (node) {
        if (node.nodeName === 'SCRIPT' && node.src) {
            var script = document.createElement('script');
            script.src = node.src;
            node.replaceWith(script)
        }
    }
}
```

**Comment by snewcomer** [comment]
👋 Great!  So does it 1. Download and/or 2. Execute the inline code? 

I would imagine it should but if it doesn't we can surely look into it!

**Comment by logankeenan** [comment]
1.  A script does not download, so it does not execute 
2. The inline scripts do not execute.

I would make a quick example if that would help too.

**Comment by snewcomer** [comment]
@logankeenan Similar to `innerHTML` which doesn't execute scripts (security reasons), I'm wondering if `replaceWith` has the same issues.  One option is to try `appendChild`.  Can you lmk if that works?

Also, another option (pending security concerns) is `fetch` the script + `eval` the response.

One last options is 

```
let range = document.createRange();
range.setStart(node, 0);
node.appendChild(
  range.createContextualFragment('<script src="..."><\/script>')
);
```

But I would try simply `appendChild` first!

**Comment by calebporzio** [comment]
I've hit this as well. I use the following snippet to evaluate <script> tags, although looking at it now, I realize this doesn't handle the case of a `src=` attribute:

```js
if (node.tagName.toLowerCase() === 'script') {
    eval(node.innerHTML)
    return false
}
```

I realize using eval() would be a CSP violation for morphdom, so I'm happy to include this in the hooks from my project.

Just weighing in in case this snippet helps others:

**Comment by logankeenan** [comment]
@snewcomer Thanks for your help! It looks like `replaceWith` will work with the onNodeAdded method and it will work when both inline scripts and external scripts are added to the DOM. 

One issue still remains. `onNodeAdded` is not fired when a node is updated and the properties/inner content is updated, but a script is not executed.  Put another way, if morphdom diffs two pieces of markup which have scripts at the same position in the tree then the script properties will get updated, but not re-execute.

If it's the intention of the morphdom to have a script execute as it's added/updated in the DOM then I feel like script tags need to be handled differently than typical elements. They need to be re-created each time they change and replaced using `replaceWith`. Otherwise, they will not execute.  I'd be happy to create a PR to accomplish that, but want to make sure that's the expected behavior of morphdom before I invest more time.  Let me know your thoughts and thank you for you time!


Updated `onNodeAdded` with replaceWith
```js
    const morphdomOptions = {
        onNodeAdded: function (node) {
            if (node.nodeName === 'SCRIPT') {
                var script = document.createElement('script');

                if (node.src) {
                    script.src = node.src;
                }

                script.innerHTML = node.innerHTML;
                node.replaceWith(script)
            }
        }
    };
```

**Comment by logankeenan** [comment]
The code below will execute JS code as it's added/updated.

```js
        let morphdomOptions = {
            onNodeAdded: function (node) {
                if (node.nodeName === 'SCRIPT') {
                    var script = document.createElement('script');
                    //copy over the attributes
                    [...toEl.attributes].forEach( attr => { script.setAttribute(attr.nodeName ,attr.nodeValue) })

                    script.innerHTML = toEl.innerHTML;
                    fromEl.replaceWith(script)
                }
            },
            onBeforeElUpdated: function (fromEl, toEl) {
                if (fromEl.nodeName === "SCRIPT" && toEl.nodeName === "SCRIPT") {
                    var script = document.createElement('script');
                    //copy over the attributes
                    [...toEl.attributes].forEach( attr => { script.setAttribute(attr.nodeName ,attr.nodeValue) })

                    script.innerHTML = toEl.innerHTML;
                    fromEl.replaceWith(script)
                    return false;
                }
                return true;
            }
        };
```

**Comment by logankeenan** [comment]
@snewcomer - thanks for your suggestion with `replaceWith` too! That worked perfectly! 🎉

**Comment by cossssmin** [comment]
> The code below will execute JS code as it's added/updated.
> 
>         let morphdomOptions = {
>             onNodeAdded: function (node) {
>                 if (node.nodeName === 'SCRIPT') {
>                     var script = document.createElement('script');
>                     //copy over the attributes
>                     [...node.attributes].forEach( attr => { script.setAttribute(attr.nodeName ,attr.nodeValue) })
> 
>                     script.innerHTML = node.innerHTML;
>                     node.replaceWith(script)
>                 }
>             },
>             onBeforeElUpdated: function (fromEl, toEl) {
>                 if (fromEl.nodeName === "SCRIPT" && toEl.nodeName === "SCRIPT") {
>                     var script = document.createElement('script');
>                     //copy over the attributes
>                     [...toEl.attributes].forEach( attr => { script.setAttribute(attr.nodeName ,attr.nodeValue) })
> 
>                     script.innerHTML = toEl.innerHTML;
>                     fromEl.replaceWith(script)
>                     return false;
>                 }
>                 return true;
>             }
>         };

This doesn't seem to work in v2.7.4, it errors out saying it failed to execute `replaceWith`.

Given this:

```html
<script>
  let res = 1 + 1;
  console.log(res);
</script>
```

... when `1 + 1` is changed to `1 + 2`, this error is thrown in the console:

```
Uncaught SyntaxError: Failed to execute 'replaceWith' on 'Element': Identifier 'res' has already been declared
at onBeforeElUpdated ...
```

The line it refers to is this:

```js
fromEl.replaceWith(script)
```
