### ISSUE TITLE
Source code for Benchmarks?

### ISSUE THREAD

**Issue by zenflow** [patrick-steele-idem/morphdom#181]
Is the source code for [the benchmarks in the README](https://github.com/patrick-steele-idem/morphdom#benchmarks) available?

I would like to rerun it with the latest versions of each package to see if the results have changed

Thanks!

**Comment by snewcomer** [comment]
They are!  The absolute path to `....../test-page.html` file can be put in the browser to view it.  Lmk if you need help doing so!
