### ISSUE TITLE
Morphing `document.body` into "<body></body>" throws an error.

### ISSUE THREAD

**Issue by utkarshkukreti** [patrick-steele-idem/morphdom#184]
Code:

```html
<script src="https://unpkg.com/morphdom@2.5.12/dist/morphdom-umd.js"></script>
<body>
<script>
  morphdom(document.body, "<body></body>");
</script>
```

Error:

```
Uncaught TypeError: Cannot read property 'nodeType' of undefined
    at morphdom (morphdom-umd.js:676)
    at a.html:4
```

Adding content to `<body>` e.g. `<body>Hello</body>` works fine.

I'll look into this as soon as I can; opening an issue so I don't forget.

**Comment by snewcomer** [comment]
The main issue here is that a document-fragment is meant to be a lightweight version of a document.  So `html` and `body` are not allowed as children in a document-fragment.  This of it as a `div` and trying to wrap `<body></body>`.  That would be invalid HTML.

However I think we can fix this. https://github.com/patrick-steele-idem/morphdom/pull/185

Let me know what you think!

**Comment by SteffenDE** [comment]
While this does not throw an error any more, it creates invalid HTML:

```html
<html>
<head>
<title>Test</title>
<script src="https://unpkg.com/morphdom@2.7.7/dist/morphdom-umd.js"></script>
</head>
<body>
<script>
  morphdom(document.body, "<body><div>Hello</div></body>");
</script>
</body>
</html>
```

<img width="247" height="169" alt="Image" src="https://github.com/user-attachments/assets/61258357-df1c-4d3f-82ad-169df3e92c82" />
