### ISSUE TITLE
curFromNode.value = curToNode.value will be delayed on mobile phone

### ISSUE THREAD

**Issue by danxinju** [patrick-steele-idem/morphdom#187]
It seems we need to update it to sourceChild.parentNode.replaceChild(document.createComment(targetChild.nodeValue), sourceChild);

**Comment by danxinju** [comment]
TextNode also has this problem, it can be fixed if we use the solution above.

**Comment by danxinju** [comment]
To see this problem we need to update the dom in a timer.

**Comment by snewcomer** [comment]
@danxinju Would you mind explaining why this is slow on mobile devices?  Thanks!

https://github.com/patrick-steele-idem/morphdom/blob/a1a023e0ac47e8ba55274f39fb2a7f6ccd7abf64/src/morphdom.js#L323

**Comment by snewcomer** [comment]
Closing for now!  Would love a bit more of an explanation.  Feel fee to re-open if need be.
