### ISSUE TITLE
Textarea problems

### ISSUE THREAD

**Issue by markuplab** [patrick-steele-idem/morphdom#19]
Textarea updates doesn't work after first input text. 

```
   <textarea></textarea>

    <script>
    document.querySelector('textarea').addEventListener('input', function(e) {
      var textarea = document.createElement('textarea');
      textarea.innerHTML = 'Hello World';
      console.log(textarea, e.currentTarget);
      morphdom(e.currentTarget, textarea);
    }, false);
   </script>
```
After first input
![2015-08-20 18 18 23](https://cloud.githubusercontent.com/assets/4974184/9383067/7cdf5610-475f-11e5-95dc-a1500eea5021.png)

After second input
![2015-08-20 18 18 15](https://cloud.githubusercontent.com/assets/4974184/9383071/86f9ef48-475f-11e5-8864-cd65c6d6fdbc.png)

Look diffirence between shadow-dom and innerHTML
![2015-08-20 18 17 06](https://cloud.githubusercontent.com/assets/4974184/9383061/57ccae36-475f-11e5-86a6-cced2090e07e.png)

I hope it help you understand issue.

![2015-08-20 18 22 07](https://cloud.githubusercontent.com/assets/4974184/9383154/1a54943c-4760-11e5-9c1f-a2786b5f17af.png)

**Comment by patrick-steele-idem** [comment]
Thanks for the detailed bug report! I was able to reproduce the issue with a test case and am working on a fix. Once the `value` setter is called on a `<textarea>` instance any changes to the value of the textarea's child text node will not impact the value. Silly DOM...

I'll publish a new version soon. Thanks!
