### ISSUE TITLE
DocumentFragment

### ISSUE THREAD

**Issue by bevacqua** [patrick-steele-idem/morphdom#20]
Shouldn't we create a `DocumentFragment` here instead? https://github.com/patrick-steele-idem/morphdom/blob/b7654c5360fbd4aa71b373bb10f576dd86516f81/lib/index.js#L14

**Comment by S-YOU** [comment]
there is no innerHTML in documentFragment.

**Comment by patrick-steele-idem** [comment]
Correct. `morphdom` just needed a container element that would allow it to use `innerHTML` to parse the HTML string into a DOM node. Newer browsers support `range.createContextualFragment(html)` which is much faster.

**Comment by bevacqua** [comment]
I'll just walk myself out
