### ISSUE TITLE
Please create a bower package

### ISSUE THREAD

**Issue by xi** [patrick-steele-idem/morphdom#22]
It is not currently possible to install this library using bower because

- it is not registered at the bower registry
- if installing via the github shorthand, the UMD build is not included

Would be great if it was possible to use bower for installation.

**Comment by patrick-steele-idem** [comment]
Personally, I don't use bower and I don't like bower, but if you want to submit a PR to support Bower then I will merge it (I realize that we will probably need to check in the `dist/` folder, sadly...). Thanks.

**Comment by patrick-steele-idem** [comment]
Doing some house cleaning... this has been implemented already so closing the issue.

**Comment by xi** [comment]
Thanks for fixing *and* for house cleaning :+1:
