### ISSUE TITLE
Browser Support?

### ISSUE THREAD

**Issue by cheft** [patrick-steele-idem/morphdom#24]
Browser Support?

**Comment by patrick-steele-idem** [comment]
We don't have continuous testings set up for all browsers, but when I loaded the test HTML page for this project in various browsers I found that it worked in browsers as old as IE8.

If anyone wants to help set up continuous testing in more browsers that would be awesome :)

**Comment by viktorbezdek** [comment]
I can confirm IE8, iOS8, iOS9, Android 4.4 browser

**Comment by patrick-steele-idem** [comment]
Good to know. Thank you for sharing, @viktorbezdek !

**Comment by viktorbezdek** [comment]
After further stress testing I can confirm also IE9, IE10, IE11, Edge, Safari 8, Safari 9, latest FF and Chrome.

I can probably make pull request with automated saucelabs tests. Let me know if you're interested.

**Comment by patrick-steele-idem** [comment]
Hey @viktorbezdek, that would be awesome if you could add automated saucelabs tests. That is not something I have done before and it would be very helpful to this project. Thanks in advance!

**Comment by snewcomer** [comment]
Browser support added to the README!  IE9 these days :)
