### ISSUE TITLE
Form selects resets to first option while morphing

### ISSUE THREAD

**Issue by viktorbezdek** [patrick-steele-idem/morphdom#26]
Not sure whether this is bug or correct behavior - if I'm morphing DOM tree containing SELECT element, first option (or option with selected attribute) is always set while morphing that tree, event if this particular element nor his children are changed.

**Comment by patrick-steele-idem** [comment]
Hey @viktorbezdek, when you rerender you should put the `selected` attribute on the `<option>` element that should be selected (i.e. `<option selected value="foo">Foo</option>`). If you don't correctly set the `selected` attribute then the existing `<option>` elements will become unselected and the selected option will go back to the first `<option>`.

Here's a similar issue that was opened: https://github.com/patrick-steele-idem/morphdom/issues/16

Also, if you don't want to have to worry about rerendering with the appropriate `<option>` having the `selected` attribute then you can copy that property before morphing the `<option>` element by doing something similar to the following:

```javascript
morphdom(fromNode, toNode, {
    onBeforeMorphEl: function(fromEl, toEl) {
        if (toEl.tagName === 'OPTION') {
            toEl.selected = fromEl.selected;
        }
    }
});
```

Not sure if that is good practice but just throwing that out there in case it helps. 

Does that answer your question?

**Comment by viktorbezdek** [comment]
Sorry for late response and yes, this does answer my question. Thanks for the clarification. Thought morphdom would transfer selectedIndex while morphing as well. Using attr selected works as expected.
