### ISSUE TITLE
Efficient update lists using the key attribute

### ISSUE THREAD

**Issue by Riim** [patrick-steele-idem/morphdom#27]
https://facebook.github.io/react/docs/multiple-components.html#dynamic-children

Hi!
Sorry, translated with translate.google.ru ((

This update faster. In addition, if the nodes are attached to component instances will be destroyed is not correct instances.
For example here https://gist.github.com/Riim/e47127fc4a88cf1e0ff9 (rista.js is this file https://github.com/Riim/rista/blob/37974a40fc83a7127af96e513a67a1fae080694c/rista.js) second element of the list `todos` is removed after three seconds, but dispose triggered on the third instance.

**Comment by Riim** [comment]
By code i understood that instead `key` using `id`.
Probably it is necessary to make such changes:
`var id = node.id;` -> `var id = node.id || node.getAttribute('key');`
because the ID must be unique for the entire document.

**Comment by Riim** [comment]
even better: `var id = node.id || options.getNodeKey && options.getNodeKey(node);`

**Comment by Riim** [comment]
[PR#28](https://github.com/patrick-steele-idem/morphdom/pull/28)

**Comment by patrick-steele-idem** [comment]
Merged PR to add support for `getNodeKey()`. Closing issue. Thanks @Riim
