### ISSUE TITLE
Support for IE7+

### ISSUE THREAD

**Issue by WesleydeSouza** [patrick-steele-idem/morphdom#32]
Current version makes use of `document.createRange` and `Element.prototype.hasAttribute`, which are unavailable on older browsers.

`createRange` can be skipped because the fallback for creating a fragment works without it.

`hasAttribute` on the other hand can't be easily replaced, but for the use case of the INPUT handler, I would suggest simply checking the getAttribute response for a truthy value.

As far as I've tested, everything else is working fine.

I will submit a pull request with those changes.

**Comment by patrick-steele-idem** [comment]
New version published with fix: `morphdom@1.1.0`

Thanks for the PR @WesleydeSouza !
