### ISSUE TITLE
innerHTML

### ISSUE THREAD

**Issue by shannonmoeller** [patrick-steele-idem/morphdom#37]
I'm using document.registerElement to create custom elements. I'd like to update the contents of the element without touching the existing parent and without creating a new parent element. In essence, the effect of setting `.innerHTML` but with morphdom's diffing.

The `childrenOnly` option gets me half way there. For example, the following does what I want:

```html
<!-- before -->
<my-dashboard>Hello</my-dashboard>
```

```js
import morphdom from 'morphdom';
import {register} from '../../scripts/util/dom';

export default register('my-dashboard', HTMLElement, {
    createdCallback() {
        // called twice
    },

    attachedCallback() {
        this.render();
    },

    render() {
        morphdom(this, '<my-dashboard>World</my-dashboard>', {
            childrenOnly: true
        });
    }
});
```
```html
<!-- after -->
<my-dashboard>World</my-dashboard>
```

However, two instances of `<my-dashboard>` are created in this case, so the `createdCallback` is fired twice. I only ever want one created. Ideally, I'd like to do something like this:

```js
import morphdom from 'morphdom';
import {register} from '../../scripts/util/dom';

export default register('my-dashboard', HTMLElement, {
    createdCallback() {
        // called once
    },

    attachedCallback() {
        this.render();
    },

    render() {
        morphdom(this, 'World', {
            innerHTML: true
        });
    }
});
```

Would you be interested in a PR that adds this? I didn't see a way to implement this using the existing hooks.

**Comment by shannonmoeller** [comment]
I've created a workaround utility method that serves my purpose for the moment, though it's likely to fail if the `toEl` is an `<li>`, `<tr>`, `<option>`, etc.

```js
export function render(fromEl, toEl, options = {}) {
    if (typeof toEl === 'string') {
        options.childrenOnly = true;
        toEl = `<div>${toEl.trim()}</div>`;
    }

    morphdom(fromEl, toEl, options);
}
```

**Comment by patrick-steele-idem** [comment]
Hey @shannonmoeller, I think your workaround is good, but I don't know if this use case will come up often enough to make a PR to `morphdom`. I would make a small tweak to your wrapper:

```javascript
export function render(fromEl, toEl, options = {}) {
    if (typeof toEl === 'string') {
        var toElContainer = document.createElement('div');
        toElContainer.innerHTML = toEl;
        options.childrenOnly = true;
        toEl = toElContainer;
    }

    morphdom(fromEl, toEl, options);
}
```

When you set the `childrenOnly` option to `true` then `morphdom` will never look at the parent element so I don't think there is a risk of failure with your workaround. 

If you still think there is a need for a PR please let me know and we can discuss some more.

**Comment by shannonmoeller** [comment]
Good call on `document.createElement` for the containing div. I can see how this would be an edge case. Thanks for the consideration and improvement.

In case it's helpful to others, this is where I ended up:

```js
export function innerHTML(fromElement, toElement, options = {}) {
    options.childrenOnly = true;

    if (typeof toElement === 'string') {
        const fragment = document.createElement('div');

        fragment.innerHTML = toElement.trim();

        toElement = fragment;
    }

    morphdom(fromElement, toElement, options);
}
```
