### ISSUE TITLE
Full page morph.

### ISSUE THREAD

**Issue by DylanPiercey** [patrick-steele-idem/morphdom#39]
Currently using jsdom for testing which could be part of the issue, but the following diff detaches the document element and fails.

```js
morphdom(document.documentElement, `
	<!DOCTYPE html>
	<html>
		<head>
			<title>Test</title>
		</head>
		<body>content</body>
	</html>
`);
```

Am I doing something wrong? Even tried removing the doctype.

---

**Edit:**

Also tried doing this directly in `Chrome Version 51.0.2680.0 canary (64-bit)` and received the following error.

```terminal
VM414:479 Uncaught DOMException: Failed to execute 'replaceChild' on 'Node': Nodes of type '#text' may not be inserted inside nodes of type '#document'
```
From:
https://github.com/patrick-steele-idem/morphdom/blob/master/lib/index.js#L478

---

**Edit2:**

Looks like the issue stems from https://github.com/patrick-steele-idem/morphdom/blob/master/lib/index.js#L38 and https://github.com/patrick-steele-idem/morphdom/blob/master/lib/index.js#L41 in my case, but it looks like `#toElement` just doesn't support anything outside of body.

**Comment by patrick-steele-idem** [comment]
I feel like that is a very uncommon use case, but if you feel this is needed we could probably support it. If you have ideas on how to support this please let me know and as long as it doesn't add too much code or complexity then I would have no objections.

I'm curious, why would you do a full page morph?

**Comment by DylanPiercey** [comment]
@patrick-steele-idem it's useful for isomorphic rendering. Currently I'm using https://github.com/tbranyen/diffhtml which does support this but am looking for something a bit more light weight.

Basically the idea is that you have a router in the browser and the server that renders the same html. Server side you send out html and browser side you morph the dom for perf and consistent state.

Currently the best approach is to use a virtual dom like React which is what I am doing but I like the idea of using alternative templating languages such as handle bars, marko etc. This makes full page html diffing appealing for me.

If you'd like to checkout my isomorphic router feel free to take a look at https://github.com/rill-js/rill which is similar to `koa@2.0` but works in the browser as well. The current `html` rendering middleware is [here](https://github.com/rill-js/html) which is very few LOC, and you can see a similar middleware which uses react vdom [here](https://github.com/rill-js/react).

**Comment by patrick-steele-idem** [comment]
The idea of running a server-side web framework is very interesting. Thanks for sharing. I went through the docs, but I'll need to take a look at the code to get a better idea of what exactly rill is doing.

As for diffing the entire page, I'm sure we can do it with a few small tweaks. Is that something you would be interested in working on? If not, I might be able to take a look soon, but I am not exactly sure how soon. Please let me know if you would be interested in adding support for a full page morph. I really think it is beneficial to avoid using a virtual DOM for rendering an entire page. The virtual DOM will always have worse performance characteristics on the server. See: http://markojs.com/blog/announcing-marko-v3/#a-note-on-marko-versus-jsxreact

**Comment by pragmadash** [comment]
@DylanPiercey sorry, for advertisement, but you might want to take a look at [Catberry.js](http://github.com/catberry/catberry). It's very similar to what you've described and it uses morphdom in its rendering engine.

**Comment by DylanPiercey** [comment]
@pragmadash I have been following Catberry from the beginning and it's a great project. Ultimately I made [Rill](https://github.com/rill-js/rill) because I grew tired of so many flux implementations and after much tinkering found "Isomorphic REST" to be a flexible, scaleable and progressive architecture for many types of apps.

@patrick-steele-idem Basically Rill is a middleware library that allows you to handle link clicks and form submissions in the browser as if they were requests to a node server. It normalizes all of the environment details so that things like "req.headers['user-agent']" are accessible with the same api in both places. I've found this makes it easy to create middleware that work in the browser, server or both with the same api with very minimal configuration.You can find a list of some middleware I have made [here](https://github.com/rill-js/rill/wiki). I hope soon to release the project once I can complete a documentation website.

**Comment by DylanPiercey** [comment]
@patrick-steele-idem Although we addressed this in my PR I am just getting around to testing this further. In my tests the diffing has been working well (visually) but I just dug a little deeper to find that it is actually discarding all nodes and resetting them on morph. Do you think you could help narrow down the cause?

**Comment by AutoSponge** [comment]
Please keep in mind that morphing HEAD tags client-side will probably not work for most use cases. For instance, og meta tags will not get morphed in time and Facebook will only see the sever-rendered ones.

Additionally, morphed script and link tags will likely become async and no longer block so you'd likely get flash of unstyled content or have scripts loading out of order.

**Comment by DylanPiercey** [comment]
@AutoSponge these points are valid, however it is still convenient to have full page diffing if you are doing universal/isomorphic JavaScript for things like the title/meta tags.

**Comment by AutoSponge** [comment]
So, this functionality was added to morphdom but it doesn't work and you're not using it?

I'm doing universal render but since I know how script/meta/link tags work, I don't try to morph them. My router updates the title and render (via morphdom) updates the body. The fact that you're trying to render the entire document on the client doesn't make your approach more convenient, it merely hand waves over the complexities of manipulating script tags, the utter waste of time manipulating meta tags, and the visual flashing caused by manipulating stylesheets on the client.

Are you opposed to that pull request being reverted?

**Comment by DylanPiercey** [comment]
@AutoSponge - That PR could be reverted. The issue was it appeared to be working but ended up actually just discarding the entire page in most cases. I just ended up rolling my own solution anyways.

Thanks both of you for getting back to me on this issue though.

**Comment by atulbhatt-system32** [comment]
> Please keep in mind that morphing HEAD tags client-side will probably not work for most use cases. For instance, og meta tags will not get morphed in time and Facebook will only see the sever-rendered ones.
> 
> Additionally, morphed script and link tags will likely become async and no longer block so you'd likely get flash of unstyled content or have scripts loading out of order.

How to deal with this though? In documentation `onBeforeNodeAdded` accept `false` but in actual it doesn't and I get the typescript error.
