### ISSUE TITLE
npm package has a 22mb `.cache` folder

### ISSUE THREAD

**Issue by laggingreflex** [patrick-steele-idem/morphdom#40]
The npm package installs with a `.cache` folder which is 22mb in size

**Comment by patrick-steele-idem** [comment]
Ouch! Thanks for letting me know.

**Comment by patrick-steele-idem** [comment]
Trimmed down version of `morphdom` published: `morphdom@1.1.4`

Thanks again for letting me know.

**Comment by laggingreflex** [comment]
no problem! was working on some size-sensitive project when I found out. Too bad [npm doesn't respect a global `~/.gitignore`](https://github.com/npm/npm/issues/5673) (expected to be fixed soon I think) in which I'm sure you may already have such folders.
