### ISSUE TITLE
Lifecycle of elements

### ISSUE THREAD

**Issue by callum** [patrick-steele-idem/morphdom#45]
I've been trying to work out a sensible way to handle the lifecycle of elements. It would be useful to know when an element is added to the document, when it's morphed, and when it's discarded. Though this functionality exists (aside from creation), it's not very well set up to allow you to respond to these changes on a per-element basis.

```js
var button = document.createElement('button')
button.on('update', function () {
  button.focus()
})
```

Some other inspiration...
https://github.com/substack/virtual-hyperscript-mount
https://github.com/substack/virtual-hyperscript-hook
virtual-dom: https://github.com/Matt-Esch/virtual-dom/blob/master/docs/hooks.md
React: http://facebook.github.io/react/docs/component-specs.html

What do you think? I would like to put a library together that wraps morphdom to provide this functionality, but I'm not sure if I've got the wrong idea.

**Comment by patrick-steele-idem** [comment]
Hey @callum 

> It would be useful to know when an element is added to the document, when it's morphed, and when it's discarded


Lifecycle event listeners are supported for all events except for when a new element is added to the DOM for the first time.

Here are the corresponding callbacks (see: :

- When it is morphed: `onBeforeMorphEl`
- When it is discared: `onNodeDiscarded`

I'm not opposed to adding support for a callback to get notified "when a new element is added" as long as there is no significant performance penalty. I could see this callback being helpful to support transition in animations.

Here is one line where an element gets inserted into the DOM for the first time, but there are a few more edge cases that would need to be handled: https://github.com/patrick-steele-idem/morphdom/blob/35919374b38605234b93eabb5340e57e461291ba/lib/index.js#L342

If you are interested in sending a PR, please let me know and we can discuss some more. At a minimum, we would want to update the automated tests to verify that the new `onNodeAdded` event is fired correctly for all nodes that are moved over into the final DOM tree.

**Comment by AutoSponge** [comment]
I would prefer an eventEmitter implementation here. Right now, I'm building apps just fine without lifecycle events. And I think the forced noops are unnecessary. If, instead, morphdom emitted events based on the actions it took, you could easily add callbacks if you want them. This would also allow morphdom to be wrapped by an Observables implementation to create a stream of changes.

Am I the only one who prefers an observer over callbacks?

**Comment by yoshuawuyts** [comment]
I'm actually not particularly fussed about lifecycle events at the level of the diffing engine anymore; [on-load](https://github.com/shama/on-load) allows hooking into `load` / `unload` events on a per-component basis. I feel it solves most use cases for lifecycle events.

The one thing it doesn't allow doing, however, is setting the equivalent of React's `.shouldComponentUpdate()`, which means that `morphdom` will always diff the complete trees. It'd  be pretty cool if we could apply some smart heuristics to determining if a particular branch of a DOM tree should be diffed (perhaps by going full Merkle-tree? - idk)

But so yeah, on the topic of lifecycle events, I think we're in a pretty good spot right now with `on-load`; don't quite see the point of changing the `morphdom` API for this.

**Comment by AutoSponge** [comment]
@yoshuawuyts Agreed. `shouldComponentUpdate` would be helpful for large interfaces to either not render out-of-viewport or delegate it to a background/idle task. While I haven't tried that yet, I suspect everything we need is already in morphdom via the `#onBefore...` hooks.

By returning `false`, I can prevent a node/tree from rendering. If I then cache that node in a map with the target that I would have rendered, I can create an idle worker to update cached nodes by calling morphdom on each cache pair.

**Comment by patrick-steele-idem** [comment]
@callum 

I like what you did with `morphdom-hooks`, but what are your thoughts on changing the API a bit:

```javascript
constant morphdomHooks = require('morphdom-hooks');
const b = document.createElement('button');
morphdomHooks.on(b, 'add', console.log.bind(console, 'button added to page!'))
morphdomHooks.on(b, 'update', console.log.bind(console, 'button updated in page!'))
morphdomHooks.on(b, 'discard', console.log.bind(console, 'button discarded from page!'))
```

I realize that makes the user code dependent on `morphdom-hooks` wherever listeners are to be added, but maybe that is okay?

@AutoSponge 

> I would prefer an eventEmitter implementation here. 

I think an EventEmitter API is better exposed as a wrapper to keep this library as small and as fast as possible.

@yoshuawuyts 

> The one thing it doesn't allow doing, however, is setting the equivalent of React's .shouldComponentUpdate(), which means that morphdom will always diff the complete trees. It'd be pretty cool if we could apply some smart heuristics to determining if a particular branch of a DOM tree should be diffed (perhaps by going full Merkle-tree? - idk)

As @AutoSponge mentioned, you can tell `morphdom` to skip parts of a DOM subtree by returning `false` in the `onBeforeElUpdated` callback.

Good discussion, but closing issue to do avoid keeping issues open for too long. If you have thoughts or comments please feel free to add here or open a new issue. Thanks all.
