### ISSUE TITLE
Support diffing #document-fragment

### ISSUE THREAD

**Issue by tbranyen** [patrick-steele-idem/morphdom#53]
Would it be possible to support the following use case:

``` js
// Example element, could be a reference to an existing DOM node.
var element = document.createElement('div');
element.innerHTML = '<span>Hello</span>';

// Build the fragment to match the children.
var fragment = document.createDocumentFragment();
fragment.appendChild(document.createElement('span'));
fragment.firstChild.appendChild(document.createTextNode('World'));

// This currently does not error, but does not diff the children.
morphdom(element, fragment);
```

Example using diffHTML: https://github.com/tbranyen/virtual-list/pull/2/commits/5500f1c0a90c47f74fc624fcbefedfbaa01b3b82#diff-9ec5f0d45b1fdec47275a0f431b03f62R75

I'd like to make this work with morphdom as well.

**Comment by tbranyen** [comment]
After more testing it appears that the children are diffed, but the parent container is removed. Either way my demo for a virtual-list module should work with morphdom. You get a container element and a fragment and need to merge the childNodes of both.

**Comment by AutoSponge** [comment]
I'm pretty sure you just need to use the `childrenOnly` flag in the options parameter.

**Comment by patrick-steele-idem** [comment]
I do think we should properly handle a document fragment, but I'm not quite sure what the "correct" behavior should be when a document fragment is provided:

- Are you intending on diffing just the child nodes of the source element with the child nodes of the target document fragment?
- Should we diff the source node with the first child of the target document fragment?
- What if there are multiple child nodes in the target document fragment?

It's easy enough to use the first child if the target is a document fragment, but that might not be expected. @tbranyen, what do you think the correct way to handle a document fragment as the target? Thanks for bringing this issue up and sorry for being slow to respond (I was out of the office last week).

**Comment by AutoSponge** [comment]
I posted a render function that should work for your documentFragment use. 

https://github.com/AutoSponge/morphdom-render

**Comment by snewcomer** [comment]
This is now supported!

https://github.com/patrick-steele-idem/morphdom/commit/3b70216e953fa053750a81d1942ef05da4b7367d
