### ISSUE TITLE
Examples look like nodejs code, but they are browser dependent

### ISSUE THREAD

**Issue by AddictArts** [patrick-steele-idem/morphdom#58]
I had hoped this could be run in nodejs and maybe it could with jsdom. Could be clearer about being only a browser implementation.

**Comment by yoshuawuyts** [comment]
Try using [raynos/document](https://github.com/Raynos/global) to render in Node:
```js
var morphdom = require('morphdom');
var document = require('global/document')

var el1 = document.createElement('div');
el1.className = 'foo';
el1.innerHTML = 'Hello John';

morphdom(el1, '<div class="bar">Hello Frank</div>');

expect(el1.className).to.equal('bar');
expect(el1.innerHTML).to.equal('Hello Frank');
```

**Comment by AddictArts** [comment]
Thanks but at least in the REPL it does not work
> morphdom(el1, '<div class="bar">Hello Frank</div>');
TypeError: Cannot read property 'nodeType' of undefined
    at morphdom (/.../node_modules/morphdom/lib/index.js:387:28)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:272:27)

**Comment by AddictArts** [comment]
I put it in a script and still no luck

/.../node_modules/morphdom/lib/index.js:29
    if (!range && document.createRange) {
                  ^

ReferenceError: document is not defined
    at toElement (/.../node_modules/morphdom/lib/index.js:29:19)

**Comment by AddictArts** [comment]
My motivation is patching html on the server. Example finding an element by css selector say and then modifying it, morph it. There is an interesting project html-element, but I didn't get far with it running into issues. Thanks again

**Comment by AutoSponge** [comment]
You probably want to use jsdom. It's how I run my tests for my morphdom projects.

**Comment by yoshuawuyts** [comment]
@AddictArts if you want to patch HTML on the server consider using [hyperstream](http://ghub.io/hyperstream); unless it's for a one-off CLI tool I'd evade doing too much dynamic stuff when building servers tho, it will definitely impact perf

**Comment by AddictArts** [comment]
@AutoSponge that is what I tried first and it doesn't work. I don't remember the error, but I had hoped that would work.

@yoshuawuyts thanks, I'll have a look. My purpose was CLI

**Comment by AutoSponge** [comment]
@AddictArts If you provide an error msg, or gist I'll try to help

**Comment by AddictArts** [comment]
Thanks @AutoSponge I tried again to see an error, but things worked this time. I did the following.
```
$ node
> let jsdom = require('jsdom')
> let morphdom = require('morphdom')
> let window = jsdom.jsdom().defaultView
> let document = window.document
> var el1 = document.createElement('div')
> el1.className = 'foo'
'foo'
> var el2 = document.createElement('div');
> el2.className = 'bar'
'bar'
> morphdom(el1, el2)
HTMLDivElement {}
> el1.className
'bar'
```

So, I think I had started this issue because the README makes it look like you should be able to copy and past into a node REPL and that is not true. While the examples in the README.md use nodejs require() they are not complete. As above I show you need jsdom. It would be nice if the examples were split for browser and nodejs. Essentially how to use it either case.

**Comment by AutoSponge** [comment]
@AddictArts, I considered making a morphdom REPL but then would have to accommodate every flavor of HTML generation. So, instead, I published a [tonicdev example](https://tonicdev.com/autosponge/morphdom-jsdom-example). Would you find it helpful to have more examples like this?

**Comment by patrick-steele-idem** [comment]
Running morphdom on the server should be supported if you can simulate the browser environment. Closing issue because I don't think there are any changes required to morphdom, but please let me know if you still have questions or thoughts.

**Comment by AddictArts** [comment]
Thanks @AutoSponge. Sorry for the belated reply. It is not a change to morphdom I was after. It is more that the README.md implies a nodejs environment "var morphdom = require('morphdom');", which mislead me. I was thinking some explanation or the example you made would clear things up. I also think morphdom could recognize the "! browser environment" and let the user know with a friendly warning.

**Comment by patrick-steele-idem** [comment]
@AddictArts if you include the universal module definition version of morphdom then a global `morphdom` variable will be created: https://github.com/patrick-steele-idem/morphdom/blob/master/dist/morphdom-umd.js

```javascript
<script type="text/javascript" src="https://npmcdn.com/morphdom/dist/morphdom-umd.min.js"></script>
<script>
window.morphdom(fromEl, toEl);
</script>
```

Do you think we need to provide docs for the usage of the UMD distribution?

**Comment by AddictArts** [comment]
@patrick-steele-idem yes, thanks. I think that would help. Looking at "Usage" it implies a build process such as browserify or webpack right? unless I missed something in the README.md. When I encountered morphdom I thought it was nodejs ready, my mistake.
