### ISSUE TITLE
Bug: Morphdom 0.1.11 can't be included in the head.

### ISSUE THREAD

**Issue by kesne** [patrick-steele-idem/morphdom#6]
There is a reference to `document.body` in morphdom [right here](https://github.com/patrick-steele-idem/morphdom/blob/master/lib/index.js#L3).

I'm using webpack and including the scripts in the head, which is causing errors because the body has not been parsed yet.

**Comment by patrick-steele-idem** [comment]
Thanks for letting us know. I put in a simple fix. New version published: `morphdom@0.1.12`
