### ISSUE TITLE
300ms morphcom call, followed by 300ms (program) (DOM) call in profiler

### ISSUE THREAD

**Issue by brandonros** [patrick-steele-idem/morphdom#65]
https://gist.github.com/anonymous/71cec266f8e04f3bf05f1fc67116c5a1

Here is a snippet of the HTML. If you could, repeat the `<tr>`s until you reach about 1.5MB.

This acts as #pick_table.

Some very small changes are made (background color, maybe a 0 to 1 in quantity, etc.)

I generate the HTML as a string inside of my app. I then flush it straight to the DOM.

Offending code:

```
var element = document.createElement('tbody');

element.innerHTML = html;

morphdom(document.querySelector('#pick_table tbody'), element);
```

Is there any way I can improve the performance? It's 300ms on my speedy MacBook Pro. I have customers complaining (this is code in a production app) that it takes 5s+ :/

I'm sure I'm doing something wrong, so any input would be greatly appreciated! Please let me know if I can provide any further information.

**Comment by patrick-steele-idem** [comment]
Hey @brandonros, the first thing that comes to mind if that it will take a long time to walk a DOM tree that large so you should use the provided hooks to skip parts of the DOM tree that you know did not change. Something similar to the following should drastically improve the performance if it is feasible for your use case:

```javascript
var morphedNode = morphdom(fromNode, toNode, {
    onBeforeElUpdated: function(fromEl, toEl) {
        var newLastModified = toEl.getAttribute('data-last-modified');
        if (newLastModified) {
            var oldLastModified = fromEl.getAttribute('data-last-modified');
            if (oldLastModified && oldLastModified === newLastModified) {
                // Skip checking this DOM subtree since the item was not modified
                return false;
            }                
        }
    }
});
```

Does it seem like that might solve your problem?

**Comment by patrick-steele-idem** [comment]
Actually, you should skip rendering parts of the DOM tree that you know did not change. If you know a portion of the DOM tree did not change then just put a placeholder node as an indicator and use the `onBeforeElUpdated` hook to skip that part of the DOM sub tree.

**Comment by brandonros** [comment]
@patrick-steele-idem On top of that, is

```
var element = document.createElement('tbody');

element.innerHTML = html;

morphdom(document.querySelector('#pick_table tbody'), element);
```

the most efficient way to do what I am trying to do? I'd really prefer to just diff two blocks of HTML and patch the differences.

**Comment by patrick-steele-idem** [comment]
> the most efficient way to do what I am trying to do? I'd really prefer to just diff two blocks of HTML and patch the differences.

Yeah, I don't see any performance issues with that code, but I would skip the query selector:

```javascript
morphdom(document.getElementById('pick_table tbody'), element);
```

**Comment by mAAdhaTTah** [comment]
Only somewhat-related question, but is this to say that you can use `onBeforeElUpdated` to "blackbox" a chunk of the DOM? Cuz that would be really helpful.

**Comment by AutoSponge** [comment]
Based on my experiment with isEqualNode [here](https://github.com/AutoSponge/morphdom-isequalnode), I would suggest to try iterating the `<tr>`s and calling morphdom on each one that fails isEqualNode. As was mentioned, you will save time by not morphing something that does not change. Then, you need to account for more or less rows by simply appending child or removing child appropriately.

Alternately, since you probably can't view that many rows at the same time, try morphing only what is in the viewport +/- a few rows for scrolling (similar to the infinite scroll technique). You can always continue morphing chunks of a hundred or so when the user stops scrolling (think of it as pre-render).

**Comment by patrick-steele-idem** [comment]
Closing this issue because I don't think this requires any changes to `morphdom`. If you have any other questions please feel free to open another Github issue.
