### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replaceChild' of null

### ISSUE THREAD

**Issue by AutoSponge** [patrick-steele-idem/morphdom#68]
I ran into this today. I tracked it down, but it wasn't obvious, so I'm posting to help anyone else who may get the same issue.

The problem was caused by generating duplicate ids. When morphdom creates an internal map it uses the id. When it reaches a second node with the same id, it seems to pull from the map. If that node is already removed from the dom, you'll get this error.

To track it down, render the view in question without running through morphdom or do so in a way that does not remove nodes. Then use a tool like HTML Codesniffer to find problems in your markup.

Cheers.

**Comment by patrick-steele-idem** [comment]
We should explore a better approach to indexing the target DOM to solve this issue and other issue. I'll close this issue, but thank you for sharing your learnings!
