### ISSUE TITLE
Button element loses class when removing name attribute in IE, Edge

### ISSUE THREAD

**Issue by karfcz** [patrick-steele-idem/morphdom#71]
Some weird bug occurs in IE only (8-11 and Edge as well). When morphing a `button` element with a class and a name attribute to a `button` that only has the class but not the name, the resulting button will have an empty class attribute.

The critical part of code is a call of `removeAttributeNode` in `morphAttrs` function: 

https://github.com/patrick-steele-idem/morphdom/blob/master/lib/index.js#L190

I don't know the reason for use of `removeAttributeNode` method, but I tried using `removeAttribute` instead and it seems to fix the bug.

The same issue can be reproduced with this simple snippet:
```js
var btn = document.createElement('button');
document.body.appendChild(btn);
btn.setAttribute('class', 'btn');
btn.setAttribute('name', 'myButton');
btn.innerHTML = "TEST";
btn.removeAttributeNode(btn.getAttributeNode('name'));
console.log(btn.getAttribute('class') === 'btn'); // => false!
```

**Comment by karfcz** [comment]
And the same happens for input and textarea elements as well, most likely for any form element.

**Comment by patrick-steele-idem** [comment]
Very interesting. Would you be interested in submitting a fix that you have tested with IE for me to review? Thanks for reporting the problem.

**Comment by karfcz** [comment]
Yes, I can try it.

**Comment by patrick-steele-idem** [comment]
Fixed by https://github.com/patrick-steele-idem/morphdom/pull/73
