### ISSUE TITLE
use informations of native dom

### ISSUE THREAD

**Issue by francescoagati** [patrick-steele-idem/morphdom#74]
Native node has more informations that a virtual node.
What do you think about using outerHTML and cssText String for a comparison between 2 nodes first of iterate attributes and childs for know if something is changed?

**Comment by AutoSponge** [comment]
morphdom does not currently use a virtual dom. DOM equality is already defined: https://dom.spec.whatwg.org/#concept-node-equals.  If you want to speed up diffing, you can use `#.isEqualNode()` or your own implementation like the example in https://github.com/patrick-steele-idem/morphdom/issues/69.

**Comment by francescoagati** [comment]
i understand but my is only a curiosity. is a.innerHTML == b.InnerHTML && a.outerHTML == b.outerHTML a comparson between string and more performant?

**Comment by AutoSponge** [comment]
The problem with string representations is that you will often get false negatives. The nodes could report unequal because attributes are in different order. We only care about the attribute keys and values being equal.

```js
var r = document.createRange()
var n1 = r.createContextualFragment('<div class="same" data-test="elm"></div>')
var n2 = r.createContextualFragment('<div data-test="elm" class="same"></div>')
n1.isEqualNode(n2) //true
n1.firstChild.outerHTML === n2.firstChild.outerHTML //false
```

**Comment by francescoagati** [comment]
right thanks :-)

**Comment by patrick-steele-idem** [comment]
It would be nice if browsers support a shallow comparison of a DOM node (don't compare child nodes). Something like the following `node.isEqualNode(otherNode, {depth: 0})`

In the mean time, I think the best option will be to loop over the attributes and compare the tag name.
