### ISSUE TITLE
how to preserve attributes

### ISSUE THREAD

**Issue by francescoagati** [patrick-steele-idem/morphdom#75]
Hi,
i am playing with morphdom. in this example i see that the dom is redraw every time. ok can i preserve the dom and node attributes every refresh frame?

http://codepen.io/francescoagati/pen/KrymZL?editors=1010

**Comment by AutoSponge** [comment]
Not sure I understand the question. When I opened the devtools, I could see the pippa element being updated non-destructively. I would say that the animation looks smoother when you write it like this:

```livescript
viewport = document.getElementById 'viewport'

counter = 0

fn = -> 
  counter++
  
  morphdom  viewport,'<div id="pippo"><div id="pippa" style="position:fixed;left:' + counter + 'px" class="baraaaa">Hello ' + counter + '</div><div>',childrenOnly:true
  
setInterval fn, 40
```

**Comment by francescoagati** [comment]
i wanna use 2 different update on with morphdom and another using vanillajs that works on the same node but on different properties. in devtools if i try to insert a new attribute, this is deleted from the update of morphdom

**Comment by AutoSponge** [comment]
Morphdom will make your existing DOM look like your "target" DOM. So, if you don't pass the target attributes to morphdom, it will get removed.

**Comment by francescoagati** [comment]
understand. one solution should be have a diff algorithm with plugins like in snabbdom.
see this example http://codepen.io/francescoagati/pen/XKZwkm where i use 2 virtual dom render, one complete and the other that works only on style properties.

**Comment by AutoSponge** [comment]
If you want to write your own function that skips morphing certain elements, use `onBeforeElUpdated` and return `false` so it won't update. If you want to change just style properties, try doing it in that same function if you return `false`. If you want to apply the style changes after the fact, use `onElUpdated`.

**Comment by francescoagati** [comment]
yes this should work goods. really thanks :-)
