### ISSUE TITLE
unexpected repaint of <select> tag

### ISSUE THREAD

**Issue by gorhgorh** [patrick-steele-idem/morphdom#84]
Hi there, i was doing a small tracker to test the choo framework that uses morphdom internally,
since trackers are music software, i have an interval running at a regular rate.

when i tried to add a ```<select>``` tag, said tag was in a component that is updated at each interval, whenever this interval happened, the select is redrawn, making it inaccessible 

here is a small test case in this [gist](https://gist.github.com/gorhgorh/11b62a08931f694200b32d29b18faa49)

That is a reduced version and same behaviour happen.

You can also see it "live" [here](http://intranetofthings.eu/) (press play, then open a select)

If i can do anything to help tracking why this is happening please ping, and thanks for morphdom

**Comment by patrick-steele-idem** [comment]
Thanks for reporting the problem, @gorhgorh. It should be resolved with `morphdom@2.1.1` (I tested the fix locally). Please let me know if you see any other issues.

**Comment by gorhgorh** [comment]
hi there, what a fast responce and fix !!! i'll update my test later tonight and report here.

**Comment by gorhgorh** [comment]
all good in my test case now 👍
