### ISSUE TITLE
Textarea problems

### ISSUE THREAD

**Issue by emanchado** [patrick-steele-idem/morphdom#88]
It seems that the issue(s) mentioned in https://github.com/yoshuawuyts/choo/issues/253 (requirebin: http://requirebin.com/?gist=e544768abd0f67a9bb621c9001ac4e02) are not completely fixed. I'm not currently able to provide a straightforward testcase, but hopefully the above is enough for you to understand what's going on.

If it's not, ping me and I'll see if I can dig a little and build a minimal test case specific for morphdom.

**Comment by AutoSponge** [comment]
There's a line in `yo-yo` https://github.com/maxogden/yo-yo/blob/master/index.js#L31

If you flip the `t`/`f` you ge the expected outcome: https://esnextb.in/?gist=81944ffdfa6ebc00827d58d7c5a91441

I'm going to close this.
