### ISSUE TITLE
question: initial use case?

### ISSUE THREAD

**Issue by alessioalex** [patrick-steele-idem/morphdom#9]
Hey @patrick-steele-idem

I was just wondering what was the initial use case, the one that made you create this library. I was thinking of `marko` async fragments, but then again `marko` only gives you missing pieces, not a complete "section" of DOM.

Thanks!

**Comment by patrick-steele-idem** [comment]
The initial use case was for rendering the HTML for a UI component and updating the DOM with the new HTML. I first integrated `morphdom` into [marko-widgets](https://github.com/marko-js/marko-widgets) to make sure it worked in a real UI component framework. For  [marko-widgets](https://github.com/marko-js/marko-widgets), a UI component is bound to a single DOM element (a `<div>`, `<span>`, etc.). Whenever the state or props of a UI component changes, `marko-widgets` will eventually rerender the UI component  (using [marko](https://github.com/marko-js/marko) in that case) to get the new HTML which is then parsed into a DOM node. `marko-widgets` then uses `morphdom` to transform the existing DOM node for UI component to match the new DOM node that was just rendered. Here's the relevant code in `marko-widgets`:

https://github.com/marko-js/marko-widgets/blob/38e1379878750fbbf324d353ec20a7b450052fa6/lib/Widget.js#L527-L563

Even if you use async functionality with marko you will eventually get the entire HTML as a single string (no gaps) when rendering in the browser. 

Does that answer your question?

**Comment by alessioalex** [comment]
Yes, thank you for the detailed reply.

**Comment by FND** [comment]
Allow me chime in here and thank you for your efforts, @patrick-steele-idem. morphdom is a wonderful little (in the best sense) library and a pleasant alternative to much more JavaScript-heavy approaches.
