### ISSUE TITLE
No changes still produce changes

### ISSUE THREAD

**Issue by caspervonb** [patrick-steele-idem/morphdom#93]
Given

```html
<script src="foo.js"></script>
<script>console.log('foo')</script>
```

Morph this into

```html
<script>console.log('foo')</script>
```

Morhdom seems to be doing two changes in scenarios like this.

1. It will morph the removed script tag that has a src attribute into the other inline script tag.
2. It will discard the second script tag.

The "right" thing to do, would be to use the best match (e.g, its more likely that node 1 was removed here rather than node 1 was mutated into the properties of node 2, and node 2 was removed).

**Comment by AutoSponge** [comment]
Unless you put an ID on the element, there is not "best match", morphdom walks the DOM tree and will use elements as it finds them, in order. 

However, if you create a hook that skips rendering SCRIPT tags with the src attribute, you can probably get what you want. Personally, I'd want it to never render script tags. I assume you're getting this from a service call or using it on the server. If the former, I think that's a serious XSS vulnerability.

**Comment by caspervonb** [comment]
> Unless you put an ID on the element, there is not "best match", morphdom walks the DOM tree and will use elements as it finds them, in order.

Yes but *should* there be? `IsEqualNode` could be used to determine if something has just changed position.

> However, if you create a hook that skips rendering SCRIPT tags with the src attribute, you can probably get what you want. Personally, I'd want it to never render script tags. I assume you're getting this from a service call or using it on the server. If the former, I think that's a serious XSS vulnerability.

*<script>* tags in particular are fairly trivial to workaround in my case, just use script.src with a prefix as an id if there is no id attribute.

And its a dev tool (watch file, update document = live editing) so not too worried about XSS.

**Comment by AutoSponge** [comment]
The isEqualNode algorithm is not trustworthy as it does not compare value. 

You case is not the general case and I'd be loathe to change behavior of the core lib when you have options that will work fine given the framework. However I won't close this in case others want to weigh in.

**Comment by tbranyen** [comment]
Could it make sense to treat the `src` attribute of a `<script/>` the same way as a Node's key?

> getNodeKey (Function(node)) - Called to get the Node's unique identifier. This is used by morphdom to rearrange elements rather than creating and destroying an element that already exists. This defaults to using the Node's id attribute.
> 

Anyways I had this thought last night for diffHTML and I'm gonna give it a try.

**Comment by patrick-steele-idem** [comment]
@tbranyen I think your suggestion to use `src` as the key would be the right thing to do, but I also agree with @AutoSponge that I'm not sure this is common enough to change the core lib. 

@caspervonb I would recommend providing your own `getNodeKey(node)` function that does something similar to the following:

```js
morphdomOptions.getNodeKey = function(node) {
    var key = node.id;
    if (!key && node.nodeName === 'SCRIPT') {
        key = node.src;
    }
    return key;
}
```

@tbranyen Unrelated, but we should sync up one today. I would love to get your thoughts on the world of DOM, DOM diffing and virtual DOM.

**Comment by tbranyen** [comment]
@patrick-steele-idem definitely! do you have a slack/irc/gitter/etc room you hang out in?

**Comment by patrick-steele-idem** [comment]
@tbranyen please ping me on Gitter. Look forward to chatting with you.

**Comment by caspervonb** [comment]
@patrick-steele-idem Am already doing that, but the issue is more on a whole IMHO. Take a collection of <li> items, remove one. All of the items are then repurposed (first match is used) rather than the one item removed, semantically this seems like the wrong thing to do.

**Comment by snewcomer** [comment]
No action items.  Closing for now...
